### PR TITLE
Fix Package.swift

### LINKED ISSUE #1750: The version tag 1.25.0rc1 is not readable by SwiftPM
SwiftPM is only able to understand semantic versioned tags. It's not able to understand the latest tag `1.25.0rc1`, but it should be able to understand `1.25.0-rc1`.

### PR DESCRIPTION
**Pull request by thebluepotato**
I'll do the change for the 2.x branch ASAP, but this fixes the showstopping bug in #1750. Major change is that Package.swift now uses the latest **tag** instead of the version number so it can be used for pre-release versions as well. It still includes the "final" version number even though it is not used in any way anymore.
**IMPORTANT**: it seems that during the release of `1.25.0-rc1` two things were overlooked:
- SPM **needs** the tag to follow semantic versioning to be able to resolve the git repo. `1.25.0rc1` does **not** follow semantic versioning whereas `1.25.0-rc1` does. I've updated make-release-package.sh to check whether the latest tag follows semantic versioning based on a modified version of the "official" RegEx: https://semver.org/. It outputs a warning if the tag does not follow semantic versioning. In that case, you should delete the tag, tag again and run `make release` again.
- The "force tag" stage at the end of `make release` defaults to **no** and seems to have been overlooked. As there are other safeguards in place (only moves the tag when nothing else has been committed), it now defaults to **yes**.

Fixes #1750 

## Checklist:

- [ ] My change is being tested and reviewed against the Sparkle 2.x branch. New changes must be developed on the 2.x development branch first.
- [x] My change is being backported to master branch (Sparkle 1.x), if deemed necessary. Please create a separate pull request for 1.x, should it be backported.
- [x] I have reviewed and commented my code, particularly in hard-to-understand areas.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] My change is or requires a documentation or localization update

## Testing

I tested and verified my change by using one or multiple of these methods:

- [ ] Sparkle Test App
- [ ] Unit Tests
- [ ] My own app
- [x] Other: Ran `make release` with tag `1.25.0-rc2`, successfully moves the tag and uses the correct url in Package.swift

macOS version tested: 11.2

### CODE REVIEW

**Comment by kornelski** [comment]
Unit tests fail, probably on git describe:

> fatal: No names found, cannot describe anything.
> Command ExternalBuildToolExecution failed with a nonzero exit code

**Comment by thebluepotato** [comment]
> Unit tests fail, probably on git describe:
> 
> > fatal: No names found, cannot describe anything.
> > Command ExternalBuildToolExecution failed with a nonzero exit code

Yes indeed! I've seen that too and I'm thinking I should either put that behind a check whether we're running GitHub actions or move it to the release-move-tag.sh script.

Have the GitHub actions replaced the `make release` workflow entirely or is it only for checks? In the first instance, this would require some deeper reworking (such as integrating the update to Package.swift within those actions)...

File: Configurations/make-release-package.sh [hunk 1]
```diff
@@ -52,17 +52,30 @@ if [ "$ACTION" = "" ] ; then
...
     #rm -rf "$CONFIGURATION_BUILD_DIR/Sparkle.xcarchive"
     zip -rqyX -9 "../Sparkle-for-Swift-Package-Manager.zip" *
+    
+    # GitHub actions set the CI environment variable to true
+    if [ "$CI" != true ]; then
+        # Get latest git tag
+        cd "$SRCROOT"
+        latest_git_tag=$(git describe --abbrev=0)
+        # Check semantic versioning
+        [[ $latest_git_tag =~ ^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$ ]] && echo "Tag $latest_git_tag follows semantic versioning" || echo "WARNING: Tag $latest_git_tag does not follow semantic versioning! SPM will not be able to resolve the repository"
```
Comment (thebluepotato) [inline Configurations/make-release-package.sh:62]: This line checks whether the latest tag follows semantic versioning and outputs a warning if it doesn't. Should this be an error instead?

File: Configurations/release-move-tag.sh [hunk 2]
```diff
@@ -10,17 +10,17 @@ if [ "$commits_since_tag" -gt 0 ]; then
     echo "Package.swift has not been committed and tag has not been moved."
 else
     # TODO: add sanity check to see if version is actually being updated or not?
-    read -p "Do you want to commit changes to Package.swift and force move tag '$latest_git_tag'? (required for Swift Package Manager release) " -n 1 -r
+    read -p "Do you want to commit changes to Package.swift and force move tag '$latest_git_tag'? (required for SPM release) [Y/n]" -n 1 -r
     echo    # (optional) move to a new line
-    if [[ $REPLY =~ ^[Yy]$ ]]; then
+    if [[ $REPLY =~ ^[Nn]$ ]]; then
```
Comment (thebluepotato) [inline Configurations/release-move-tag.sh:15]: The prompt now defaults to YES. Since this is only ever relevant when you've literally just tagged a new release and run `make release` afterwards, should the prompt be skipped entirely? In other words, should Package.swift *always* be updated, committed and the tag moved in those circumstances?

**Comment by zorgiepoo** [comment]
(changes look reasonable on my end, will trust best judgement here)

File: Configurations/make-release-package.sh (hunk 1 above)
Comment (kornelski) [reply Configurations/make-release-package.sh:62]: Yeah, it should be an error.

File: Configurations/release-move-tag.sh (hunk 2 above)
Comment (kornelski) [reply Configurations/release-move-tag.sh:15]: Prompt is fine

**Review by kornelski — APPROVED** [review]

File: Configurations/make-release-package.sh (hunk 1 above)
Comment (thebluepotato) [reply Configurations/make-release-package.sh]: Ok, it's now an error!
